#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jumblist.LinqToSqlDataProvider
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="JumblistDatabase")]
	public partial class JumblistDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFeed(Feed instance);
    partial void UpdateFeed(Feed instance);
    partial void DeleteFeed(Feed instance);
    partial void InsertMessage(Message instance);
    partial void UpdateMessage(Message instance);
    partial void DeleteMessage(Message instance);
    partial void InsertAuthor(Author instance);
    partial void UpdateAuthor(Author instance);
    partial void DeleteAuthor(Author instance);
    #endregion
		
		public JumblistDataContext() : 
				base(global::Jumblist.LinqToSqlDataProvider.Properties.Settings.Default.JumblistDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JumblistDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JumblistDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JumblistDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JumblistDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Feed> Feeds
		{
			get
			{
				return this.GetTable<Feed>();
			}
		}
		
		public System.Data.Linq.Table<Message> Messages
		{
			get
			{
				return this.GetTable<Message>();
			}
		}
		
		public System.Data.Linq.Table<Author> Authors
		{
			get
			{
				return this.GetTable<Author>();
			}
		}
		
		[Function(Name="dbo.DistanceBetween", IsComposable=true)]
		public System.Nullable<float> DistanceBetween([Parameter(Name="Lat1", DbType="Real")] System.Nullable<float> lat1, [Parameter(Name="Long1", DbType="Real")] System.Nullable<float> long1, [Parameter(Name="Lat2", DbType="Real")] System.Nullable<float> lat2, [Parameter(Name="Long2", DbType="Real")] System.Nullable<float> long2)
		{
			return ((System.Nullable<float>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lat1, long1, lat2, long2).ReturnValue));
		}
		
		[Function(Name="dbo.NearestMessages", IsComposable=true)]
		public IQueryable<NearestMessagesResult> NearestMessages([Parameter(DbType="Real")] System.Nullable<float> lat, [Parameter(Name="long", DbType="Real")] System.Nullable<float> @long, [Parameter(DbType="Int")] System.Nullable<int> distance)
		{
			return this.CreateMethodCallQuery<NearestMessagesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lat, @long, distance);
		}
	}
	
	[Table(Name="dbo.Feeds")]
	public partial class Feed : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FeedId;
		
		private string _FeedUrl;
		
		private string _FeedUsername;
		
		private string _FeedPassword;
		
		private double _FeedCheckIntervalTicks;
		
		private string _FeedType;
		
		private string _FeedLastUpdateStatus;
		
		private System.Nullable<System.DateTime> _FeedLastUpdateDateTime;
		
		private EntitySet<Message> _Messages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFeedIdChanging(int value);
    partial void OnFeedIdChanged();
    partial void OnFeedUrlChanging(string value);
    partial void OnFeedUrlChanged();
    partial void OnFeedUsernameChanging(string value);
    partial void OnFeedUsernameChanged();
    partial void OnFeedPasswordChanging(string value);
    partial void OnFeedPasswordChanged();
    partial void OnFeedCheckIntervalTicksChanging(double value);
    partial void OnFeedCheckIntervalTicksChanged();
    partial void OnFeedTypeChanging(string value);
    partial void OnFeedTypeChanged();
    partial void OnFeedLastUpdateStatusChanging(string value);
    partial void OnFeedLastUpdateStatusChanged();
    partial void OnFeedLastUpdateDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFeedLastUpdateDateTimeChanged();
    #endregion
		
		public Feed()
		{
			this._Messages = new EntitySet<Message>(new Action<Message>(this.attach_Messages), new Action<Message>(this.detach_Messages));
			OnCreated();
		}
		
		[Column(Storage="_FeedId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FeedId
		{
			get
			{
				return this._FeedId;
			}
			set
			{
				if ((this._FeedId != value))
				{
					this.OnFeedIdChanging(value);
					this.SendPropertyChanging();
					this._FeedId = value;
					this.SendPropertyChanged("FeedId");
					this.OnFeedIdChanged();
				}
			}
		}
		
		[Column(Storage="_FeedUrl", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string FeedUrl
		{
			get
			{
				return this._FeedUrl;
			}
			set
			{
				if ((this._FeedUrl != value))
				{
					this.OnFeedUrlChanging(value);
					this.SendPropertyChanging();
					this._FeedUrl = value;
					this.SendPropertyChanged("FeedUrl");
					this.OnFeedUrlChanged();
				}
			}
		}
		
		[Column(Storage="_FeedUsername", DbType="NVarChar(250)")]
		public string FeedUsername
		{
			get
			{
				return this._FeedUsername;
			}
			set
			{
				if ((this._FeedUsername != value))
				{
					this.OnFeedUsernameChanging(value);
					this.SendPropertyChanging();
					this._FeedUsername = value;
					this.SendPropertyChanged("FeedUsername");
					this.OnFeedUsernameChanged();
				}
			}
		}
		
		[Column(Storage="_FeedPassword", DbType="NVarChar(250)")]
		public string FeedPassword
		{
			get
			{
				return this._FeedPassword;
			}
			set
			{
				if ((this._FeedPassword != value))
				{
					this.OnFeedPasswordChanging(value);
					this.SendPropertyChanging();
					this._FeedPassword = value;
					this.SendPropertyChanged("FeedPassword");
					this.OnFeedPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_FeedCheckIntervalTicks", DbType="Float NOT NULL")]
		public double FeedCheckIntervalTicks
		{
			get
			{
				return this._FeedCheckIntervalTicks;
			}
			set
			{
				if ((this._FeedCheckIntervalTicks != value))
				{
					this.OnFeedCheckIntervalTicksChanging(value);
					this.SendPropertyChanging();
					this._FeedCheckIntervalTicks = value;
					this.SendPropertyChanged("FeedCheckIntervalTicks");
					this.OnFeedCheckIntervalTicksChanged();
				}
			}
		}
		
		[Column(Storage="_FeedType", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string FeedType
		{
			get
			{
				return this._FeedType;
			}
			set
			{
				if ((this._FeedType != value))
				{
					this.OnFeedTypeChanging(value);
					this.SendPropertyChanging();
					this._FeedType = value;
					this.SendPropertyChanged("FeedType");
					this.OnFeedTypeChanged();
				}
			}
		}
		
		[Column(Storage="_FeedLastUpdateStatus", DbType="NVarChar(50)")]
		public string FeedLastUpdateStatus
		{
			get
			{
				return this._FeedLastUpdateStatus;
			}
			set
			{
				if ((this._FeedLastUpdateStatus != value))
				{
					this.OnFeedLastUpdateStatusChanging(value);
					this.SendPropertyChanging();
					this._FeedLastUpdateStatus = value;
					this.SendPropertyChanged("FeedLastUpdateStatus");
					this.OnFeedLastUpdateStatusChanged();
				}
			}
		}
		
		[Column(Storage="_FeedLastUpdateDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> FeedLastUpdateDateTime
		{
			get
			{
				return this._FeedLastUpdateDateTime;
			}
			set
			{
				if ((this._FeedLastUpdateDateTime != value))
				{
					this.OnFeedLastUpdateDateTimeChanging(value);
					this.SendPropertyChanging();
					this._FeedLastUpdateDateTime = value;
					this.SendPropertyChanged("FeedLastUpdateDateTime");
					this.OnFeedLastUpdateDateTimeChanged();
				}
			}
		}
		
		[Association(Name="Feed_Message", Storage="_Messages", ThisKey="FeedId", OtherKey="FeedId")]
		public EntitySet<Message> Messages
		{
			get
			{
				return this._Messages;
			}
			set
			{
				this._Messages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Messages(Message entity)
		{
			this.SendPropertyChanging();
			entity.Feed = this;
		}
		
		private void detach_Messages(Message entity)
		{
			this.SendPropertyChanging();
			entity.Feed = null;
		}
	}
	
	[Table(Name="dbo.Messages")]
	public partial class Message : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MessageId;
		
		private string _MessageUrl;
		
		private string _MessageTitle;
		
		private string _MessageSummary;
		
		private string _MessageBody;
		
		private int _MessageYahooId;
		
		private string _MessageYahooGroup;
		
		private System.DateTime _MessageDateTime;
		
		private string _MessageType;
		
		private string _MessageKeywordList;
		
		private string _MessageLocation;
		
		private string _MessageCountry;
		
		private System.Nullable<double> _MessageLatitude;
		
		private System.Nullable<double> _MessageLongitude;
		
		private System.Nullable<bool> _MessageDisplay;
		
		private int _AuthorId;
		
		private int _FeedId;
		
		private EntityRef<Feed> _Feed;
		
		private EntityRef<Author> _Author;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMessageIdChanging(int value);
    partial void OnMessageIdChanged();
    partial void OnMessageUrlChanging(string value);
    partial void OnMessageUrlChanged();
    partial void OnMessageTitleChanging(string value);
    partial void OnMessageTitleChanged();
    partial void OnMessageSummaryChanging(string value);
    partial void OnMessageSummaryChanged();
    partial void OnMessageBodyChanging(string value);
    partial void OnMessageBodyChanged();
    partial void OnMessageYahooIdChanging(int value);
    partial void OnMessageYahooIdChanged();
    partial void OnMessageYahooGroupChanging(string value);
    partial void OnMessageYahooGroupChanged();
    partial void OnMessageDateTimeChanging(System.DateTime value);
    partial void OnMessageDateTimeChanged();
    partial void OnMessageTypeChanging(string value);
    partial void OnMessageTypeChanged();
    partial void OnMessageKeywordListChanging(string value);
    partial void OnMessageKeywordListChanged();
    partial void OnMessageLocationChanging(string value);
    partial void OnMessageLocationChanged();
    partial void OnMessageCountryChanging(string value);
    partial void OnMessageCountryChanged();
    partial void OnMessageLatitudeChanging(System.Nullable<double> value);
    partial void OnMessageLatitudeChanged();
    partial void OnMessageLongitudeChanging(System.Nullable<double> value);
    partial void OnMessageLongitudeChanged();
    partial void OnMessageDisplayChanging(System.Nullable<bool> value);
    partial void OnMessageDisplayChanged();
    partial void OnAuthorIdChanging(int value);
    partial void OnAuthorIdChanged();
    partial void OnFeedIdChanging(int value);
    partial void OnFeedIdChanged();
    #endregion
		
		public Message()
		{
			this._Feed = default(EntityRef<Feed>);
			this._Author = default(EntityRef<Author>);
			OnCreated();
		}
		
		[Column(Storage="_MessageId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MessageId
		{
			get
			{
				return this._MessageId;
			}
			set
			{
				if ((this._MessageId != value))
				{
					this.OnMessageIdChanging(value);
					this.SendPropertyChanging();
					this._MessageId = value;
					this.SendPropertyChanged("MessageId");
					this.OnMessageIdChanged();
				}
			}
		}
		
		[Column(Storage="_MessageUrl", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string MessageUrl
		{
			get
			{
				return this._MessageUrl;
			}
			set
			{
				if ((this._MessageUrl != value))
				{
					this.OnMessageUrlChanging(value);
					this.SendPropertyChanging();
					this._MessageUrl = value;
					this.SendPropertyChanged("MessageUrl");
					this.OnMessageUrlChanged();
				}
			}
		}
		
		[Column(Storage="_MessageTitle", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string MessageTitle
		{
			get
			{
				return this._MessageTitle;
			}
			set
			{
				if ((this._MessageTitle != value))
				{
					this.OnMessageTitleChanging(value);
					this.SendPropertyChanging();
					this._MessageTitle = value;
					this.SendPropertyChanged("MessageTitle");
					this.OnMessageTitleChanged();
				}
			}
		}
		
		[Column(Storage="_MessageSummary", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string MessageSummary
		{
			get
			{
				return this._MessageSummary;
			}
			set
			{
				if ((this._MessageSummary != value))
				{
					this.OnMessageSummaryChanging(value);
					this.SendPropertyChanging();
					this._MessageSummary = value;
					this.SendPropertyChanged("MessageSummary");
					this.OnMessageSummaryChanged();
				}
			}
		}
		
		[Column(Storage="_MessageBody", DbType="NVarChar(250)")]
		public string MessageBody
		{
			get
			{
				return this._MessageBody;
			}
			set
			{
				if ((this._MessageBody != value))
				{
					this.OnMessageBodyChanging(value);
					this.SendPropertyChanging();
					this._MessageBody = value;
					this.SendPropertyChanged("MessageBody");
					this.OnMessageBodyChanged();
				}
			}
		}
		
		[Column(Storage="_MessageYahooId", DbType="Int NOT NULL")]
		public int MessageYahooId
		{
			get
			{
				return this._MessageYahooId;
			}
			set
			{
				if ((this._MessageYahooId != value))
				{
					this.OnMessageYahooIdChanging(value);
					this.SendPropertyChanging();
					this._MessageYahooId = value;
					this.SendPropertyChanged("MessageYahooId");
					this.OnMessageYahooIdChanged();
				}
			}
		}
		
		[Column(Storage="_MessageYahooGroup", DbType="NVarChar(250)")]
		public string MessageYahooGroup
		{
			get
			{
				return this._MessageYahooGroup;
			}
			set
			{
				if ((this._MessageYahooGroup != value))
				{
					this.OnMessageYahooGroupChanging(value);
					this.SendPropertyChanging();
					this._MessageYahooGroup = value;
					this.SendPropertyChanged("MessageYahooGroup");
					this.OnMessageYahooGroupChanged();
				}
			}
		}
		
		[Column(Storage="_MessageDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime MessageDateTime
		{
			get
			{
				return this._MessageDateTime;
			}
			set
			{
				if ((this._MessageDateTime != value))
				{
					this.OnMessageDateTimeChanging(value);
					this.SendPropertyChanging();
					this._MessageDateTime = value;
					this.SendPropertyChanged("MessageDateTime");
					this.OnMessageDateTimeChanged();
				}
			}
		}
		
		[Column(Storage="_MessageType", DbType="NVarChar(250)")]
		public string MessageType
		{
			get
			{
				return this._MessageType;
			}
			set
			{
				if ((this._MessageType != value))
				{
					this.OnMessageTypeChanging(value);
					this.SendPropertyChanging();
					this._MessageType = value;
					this.SendPropertyChanged("MessageType");
					this.OnMessageTypeChanged();
				}
			}
		}
		
		[Column(Storage="_MessageKeywordList", DbType="NVarChar(250)")]
		public string MessageKeywordList
		{
			get
			{
				return this._MessageKeywordList;
			}
			set
			{
				if ((this._MessageKeywordList != value))
				{
					this.OnMessageKeywordListChanging(value);
					this.SendPropertyChanging();
					this._MessageKeywordList = value;
					this.SendPropertyChanged("MessageKeywordList");
					this.OnMessageKeywordListChanged();
				}
			}
		}
		
		[Column(Storage="_MessageLocation", DbType="NVarChar(250)")]
		public string MessageLocation
		{
			get
			{
				return this._MessageLocation;
			}
			set
			{
				if ((this._MessageLocation != value))
				{
					this.OnMessageLocationChanging(value);
					this.SendPropertyChanging();
					this._MessageLocation = value;
					this.SendPropertyChanged("MessageLocation");
					this.OnMessageLocationChanged();
				}
			}
		}
		
		[Column(Storage="_MessageCountry", DbType="NVarChar(250)")]
		public string MessageCountry
		{
			get
			{
				return this._MessageCountry;
			}
			set
			{
				if ((this._MessageCountry != value))
				{
					this.OnMessageCountryChanging(value);
					this.SendPropertyChanging();
					this._MessageCountry = value;
					this.SendPropertyChanged("MessageCountry");
					this.OnMessageCountryChanged();
				}
			}
		}
		
		[Column(Storage="_MessageLatitude", DbType="Float")]
		public System.Nullable<double> MessageLatitude
		{
			get
			{
				return this._MessageLatitude;
			}
			set
			{
				if ((this._MessageLatitude != value))
				{
					this.OnMessageLatitudeChanging(value);
					this.SendPropertyChanging();
					this._MessageLatitude = value;
					this.SendPropertyChanged("MessageLatitude");
					this.OnMessageLatitudeChanged();
				}
			}
		}
		
		[Column(Storage="_MessageLongitude", DbType="Float")]
		public System.Nullable<double> MessageLongitude
		{
			get
			{
				return this._MessageLongitude;
			}
			set
			{
				if ((this._MessageLongitude != value))
				{
					this.OnMessageLongitudeChanging(value);
					this.SendPropertyChanging();
					this._MessageLongitude = value;
					this.SendPropertyChanged("MessageLongitude");
					this.OnMessageLongitudeChanged();
				}
			}
		}
		
		[Column(Storage="_MessageDisplay", DbType="Bit")]
		public System.Nullable<bool> MessageDisplay
		{
			get
			{
				return this._MessageDisplay;
			}
			set
			{
				if ((this._MessageDisplay != value))
				{
					this.OnMessageDisplayChanging(value);
					this.SendPropertyChanging();
					this._MessageDisplay = value;
					this.SendPropertyChanged("MessageDisplay");
					this.OnMessageDisplayChanged();
				}
			}
		}
		
		[Column(Storage="_AuthorId", DbType="Int NOT NULL")]
		public int AuthorId
		{
			get
			{
				return this._AuthorId;
			}
			set
			{
				if ((this._AuthorId != value))
				{
					if (this._Author.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAuthorIdChanging(value);
					this.SendPropertyChanging();
					this._AuthorId = value;
					this.SendPropertyChanged("AuthorId");
					this.OnAuthorIdChanged();
				}
			}
		}
		
		[Column(Storage="_FeedId", DbType="Int NOT NULL")]
		public int FeedId
		{
			get
			{
				return this._FeedId;
			}
			set
			{
				if ((this._FeedId != value))
				{
					if (this._Feed.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFeedIdChanging(value);
					this.SendPropertyChanging();
					this._FeedId = value;
					this.SendPropertyChanged("FeedId");
					this.OnFeedIdChanged();
				}
			}
		}
		
		[Association(Name="Feed_Message", Storage="_Feed", ThisKey="FeedId", OtherKey="FeedId", IsForeignKey=true)]
		public Feed Feed
		{
			get
			{
				return this._Feed.Entity;
			}
			set
			{
				Feed previousValue = this._Feed.Entity;
				if (((previousValue != value) 
							|| (this._Feed.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Feed.Entity = null;
						previousValue.Messages.Remove(this);
					}
					this._Feed.Entity = value;
					if ((value != null))
					{
						value.Messages.Add(this);
						this._FeedId = value.FeedId;
					}
					else
					{
						this._FeedId = default(int);
					}
					this.SendPropertyChanged("Feed");
				}
			}
		}
		
		[Association(Name="Author_Message", Storage="_Author", ThisKey="AuthorId", OtherKey="AuthorId", IsForeignKey=true)]
		public Author Author
		{
			get
			{
				return this._Author.Entity;
			}
			set
			{
				Author previousValue = this._Author.Entity;
				if (((previousValue != value) 
							|| (this._Author.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Author.Entity = null;
						previousValue.Messages.Remove(this);
					}
					this._Author.Entity = value;
					if ((value != null))
					{
						value.Messages.Add(this);
						this._AuthorId = value.AuthorId;
					}
					else
					{
						this._AuthorId = default(int);
					}
					this.SendPropertyChanged("Author");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Authors")]
	public partial class Author : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AuthorId;
		
		private string _AuthorName;
		
		private string _AuthorProfile;
		
		private string _AuthorEmailHttpLink;
		
		private EntitySet<Message> _Messages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuthorIdChanging(int value);
    partial void OnAuthorIdChanged();
    partial void OnAuthorNameChanging(string value);
    partial void OnAuthorNameChanged();
    partial void OnAuthorProfileChanging(string value);
    partial void OnAuthorProfileChanged();
    partial void OnAuthorEmailHttpLinkChanging(string value);
    partial void OnAuthorEmailHttpLinkChanged();
    #endregion
		
		public Author()
		{
			this._Messages = new EntitySet<Message>(new Action<Message>(this.attach_Messages), new Action<Message>(this.detach_Messages));
			OnCreated();
		}
		
		[Column(Storage="_AuthorId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AuthorId
		{
			get
			{
				return this._AuthorId;
			}
			set
			{
				if ((this._AuthorId != value))
				{
					this.OnAuthorIdChanging(value);
					this.SendPropertyChanging();
					this._AuthorId = value;
					this.SendPropertyChanged("AuthorId");
					this.OnAuthorIdChanged();
				}
			}
		}
		
		[Column(Storage="_AuthorName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string AuthorName
		{
			get
			{
				return this._AuthorName;
			}
			set
			{
				if ((this._AuthorName != value))
				{
					this.OnAuthorNameChanging(value);
					this.SendPropertyChanging();
					this._AuthorName = value;
					this.SendPropertyChanged("AuthorName");
					this.OnAuthorNameChanged();
				}
			}
		}
		
		[Column(Storage="_AuthorProfile", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string AuthorProfile
		{
			get
			{
				return this._AuthorProfile;
			}
			set
			{
				if ((this._AuthorProfile != value))
				{
					this.OnAuthorProfileChanging(value);
					this.SendPropertyChanging();
					this._AuthorProfile = value;
					this.SendPropertyChanged("AuthorProfile");
					this.OnAuthorProfileChanged();
				}
			}
		}
		
		[Column(Storage="_AuthorEmailHttpLink", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string AuthorEmailHttpLink
		{
			get
			{
				return this._AuthorEmailHttpLink;
			}
			set
			{
				if ((this._AuthorEmailHttpLink != value))
				{
					this.OnAuthorEmailHttpLinkChanging(value);
					this.SendPropertyChanging();
					this._AuthorEmailHttpLink = value;
					this.SendPropertyChanged("AuthorEmailHttpLink");
					this.OnAuthorEmailHttpLinkChanged();
				}
			}
		}
		
		[Association(Name="Author_Message", Storage="_Messages", ThisKey="AuthorId", OtherKey="AuthorId")]
		public EntitySet<Message> Messages
		{
			get
			{
				return this._Messages;
			}
			set
			{
				this._Messages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Messages(Message entity)
		{
			this.SendPropertyChanging();
			entity.Author = this;
		}
		
		private void detach_Messages(Message entity)
		{
			this.SendPropertyChanging();
			entity.Author = null;
		}
	}
	
	public partial class NearestMessagesResult
	{
		
		private int _MessageId;
		
		public NearestMessagesResult()
		{
		}
		
		[Column(Storage="_MessageId", DbType="Int NOT NULL")]
		public int MessageId
		{
			get
			{
				return this._MessageId;
			}
			set
			{
				if ((this._MessageId != value))
				{
					this._MessageId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
